[global]
# Your Spotify account name.
username = viserystargyren

# Your Spotify account password.
password = theburgerman9029

# device name
device_name = Arch

# device type
device_type = computer

# inital volume
initial_volume = 100

# volume normalisation
#volume_normalisation = true

# pregain
normalisation_pregain = -10

# backend
backend = pulseaudio

# mixer
mixer = PCM

# enable cache
no-audio-cache = false

# cache directory
cache_path = /home/will/spotify-cache
