require("vim._core.ui2").enable({})
require("options")
require("keymaps")
require("commands")
require("packages")
require("lsp")
-- vim.cmd.colorscheme("<scheme>")
--
require("nvim-autopairs").setup({})
require("colorizer").setup({})
